const baseurl = process.env.REACT_APP_BACKEND_URL;

const URL_LOGIN = `${baseurl}users/login`;

const URL_GET_ALL_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}`;
const URL_ADD_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}stock/report-global`;
const URL_DELETE_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}`;
const URL_UPDATE_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}`;

const URL_GET_ALL_KIRIM_SALDO_TAHUN = `${baseurl}`;
const URL_ADD_KIRIM_SALDO_TAHUN = `${baseurl}`;
const URL_DELETE_KIRIM_SALDO_TAHUN = `${baseurl}`;
const URL_UPDATE_KIRIM_SALDO_TAHUN = `${baseurl}`;

const URL_GET_ALL_STOCK_ADMIN = `${baseurl}`;
const URL_ADD_STOCK_ADMIN = `${baseurl}`;
const URL_DELETE_STOCK_ADMIN = `${baseurl}`;
const URL_UPDATE_STOCK_ADMIN = `${baseurl}`;

const URL_GET_ALL_SALDO_BAHAN = `${baseurl}`;
const URL_ADD_SALDO_BAHAN = `${baseurl}`;
const URL_DELETE_SALDO_BAHAN = `${baseurl}`;
const URL_UPDATE_SALDO_BAHAN = `${baseurl}`;

const URL_GET_ALL_KIRIM_DESIAN = `${baseurl}`;
const URL_ADD_KIRIM_DESIAN = `${baseurl}`;
const URL_DELETE_KIRIM_DESIAN = `${baseurl}`;
const URL_UPDATE_KIRIM_DESIAN = `${baseurl}`;

const URL_GET_ALL_KIRIM_SALDO_DIVISI = `${baseurl}`;
const URL_ADD_KIRIM_SALDO_DIVISI = `${baseurl}`;
const URL_DELETE_KIRIM_SALDO_DIVISI = `${baseurl}`;
const URL_UPDATE_KIRIM_SALDO_DIVISI = `${baseurl}`;

const data = {
  URL_LOGIN,
  URL_GET_ALL_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_ADD_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_DELETE_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_UPDATE_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_GET_ALL_KIRIM_SALDO_TAHUN,
  URL_ADD_KIRIM_SALDO_TAHUN,
  URL_DELETE_KIRIM_SALDO_TAHUN,
  URL_UPDATE_KIRIM_SALDO_TAHUN,
  URL_GET_ALL_STOCK_ADMIN,
  URL_ADD_STOCK_ADMIN,
  URL_DELETE_STOCK_ADMIN,
  URL_UPDATE_STOCK_ADMIN,
  URL_GET_ALL_SALDO_BAHAN,
  URL_ADD_SALDO_BAHAN,
  URL_DELETE_SALDO_BAHAN,
  URL_UPDATE_SALDO_BAHAN,
  URL_GET_ALL_KIRIM_DESIAN,
  URL_ADD_KIRIM_DESIAN,
  URL_DELETE_KIRIM_DESIAN,
  URL_UPDATE_KIRIM_DESIAN,
  URL_GET_ALL_KIRIM_SALDO_DIVISI,
  URL_ADD_KIRIM_SALDO_DIVISI,
  URL_DELETE_KIRIM_SALDO_DIVISI,
  URL_UPDATE_KIRIM_SALDO_DIVISI,
};

export default data;
